"""
Compliance report models for Vāhan-Rakshak
"""

from pydantic import BaseModel
from typing import List, Optional
from enum import Enum
from datetime import datetime


class ComplianceStatus(str, Enum):
    """Compliance check status"""
    APPROVED = "approved"
    VIOLATION = "violation"
    WARNING = "warning"
    SUSPENDED = "suspended"


class ViolationType(str, Enum):
    """Types of violations"""
    UNDECLARED_CARGO = "undeclared_cargo"
    PROHIBITED_HAZMAT = "prohibited_hazmat"
    OVERWEIGHT = "overweight"
    INCOMPLETE_DOCUMENTATION = "incomplete_documentation"
    SENSOR_MALFUNCTION = "sensor_malfunction"
    VEHICLE_UNSAFE = "vehicle_unsafe"
    DRIVER_UNQUALIFIED = "driver_unqualified"
    OTHER = "other"


class ComplianceReport(BaseModel):
    """Compliance report generated by Gatekeeper"""
    report_id: str
    manifest_id: str
    vehicle_id: str
    vehicle_number: str
    status: ComplianceStatus
    check_timestamp: datetime = datetime.now()
    gatekeeper_agent_id: str = "gatekeeper_v1"
    
    violations: List[ViolationType] = []
    violation_details: str = ""
    
    # Evidence
    cargo_photo_path: Optional[str] = None
    qr_scan_data: Optional[str] = None
    
    # RTO submission
    submitted_to_rto: bool = False
    rto_submission_timestamp: Optional[datetime] = None
    rto_reference_id: Optional[str] = None
    
    # Actions taken
    vehicle_ignition_locked: bool = False
    departure_blocked: bool = False
    
    # Remarks
    notes: str = ""

    class Config:
        use_enum_values = True

    def has_critical_violations(self) -> bool:
        """Check if report has critical violations"""
        critical = {
            ViolationType.PROHIBITED_HAZMAT,
            ViolationType.VEHICLE_UNSAFE,
            ViolationType.SENSOR_MALFUNCTION
        }
        return any(v in critical for v in self.violations)

    def add_violation(self, violation_type: ViolationType, detail: str = "") -> None:
        """Add a violation to the report"""
        if violation_type not in self.violations:
            self.violations.append(violation_type)
        self.violation_details += f"\n- {violation_type.value}: {detail}"
